### PR TITLE
Added support for non-JSON

### LINKED ISSUE #86: Library can corrupt data if default charset is not UTF-8
The Java Client Library can corrupt the data returned by API calls if the default charset is not UTF-8. For example, if a device definition contains characters that are not in Windows code page Cp1252, and ApiClient.getAllDevices() is called to retrieve the device details, and the default charset is Cp1252, the characters will be corrupted.

The system should handle all Unicode characters without corruption.  The reason for the error is the use of the InputStreamReader(InputStream) constructor in APIClient.java:

```
private String readContent(HttpResponse response, String method)
throws IllegalStateException, IOException {

BufferedReader br = new BufferedReader(new InputStreamReader(response.getEntity().getContent()));
```

This constructor uses the default charset. The code should explicitly state the charset like this:

```
BufferedReader br = new BufferedReader(new InputStreamReader(response.getEntity().getContent(), StandardCharsets.UTF_8));
```

There are further instances of InputStreamReader(InputStream) in AbstractClient.java that should be investigated and if necessary corrected.

### PR DESCRIPTION
**Pull request by amitmangalvedkar**
Fixes #86 
Also fixes non-JSON strings as HTTP post from device

### CODE REVIEW

**Review by CaroMac — CHANGES_REQUESTED** [review]
https://docs.internetofthings.ibmcloud.com/swagger/v0002.html is an old api link. Please see https://console.bluemix.net/docs/services/IoT/reference/api.html#api_http for the new api links.

**Review by CaroMac — CHANGES_REQUESTED** [review]
For the error code 400, I think that bad syntax might be more meaningful that bad value? Also when you say "no body" do you mean that the body is missing or that the body is invalid?

**Review by CaroMac — COMMENTED** [review]
This method has been kept only for backward compatibility and would soon be deprecated
 -
suggest
This method is maintained only for backward compatibility, and will soon be deprecated.

**Review by CaroMac — CHANGES_REQUESTED** [review]
Failure publishing event > suggest Failed to publish event

**Review by CaroMac — CHANGES_REQUESTED** [review]
This test expects a properties file containing the device registration details. Failing to provide the same, the test will return immediately and show as passed.

Should read something like - 


This test requires a properties file that contains device registration details. If a 
valid properties file is not provided, the test ....

I am not sure what to suggest for the last part of the sentence. Current wording suggests that the test completes and is shown as successful even if no file has been provided?? It seems slightly odd.

**Review by sathipal — APPROVED** [review]

**Pull request merged**
